### ISSUE TITLE
Divvun-installer fails to start

### ISSUE THREAD

**Issue by albbas** [divvun/divvun-installer-windows#14]
I already had Divvun-installer nightly 202007-something installed. I uninstalled that and everything Divvun from Control Panel, restarting on each request.
Then downloaded Divvun-installer from divvun.org.
Chose lule sami speller, and north sami speller and keyboard. The installation of those stopped with an error (did not take a screenshot of that error message).
According to Control Panel, the lule sami speller is installed, but not the northern sami packages I chose.

Then, when I start Divvun-installer, I get the message below.
![start-divvun-installer](https://user-images.githubusercontent.com/75695/91845272-224df400-ec59-11ea-96b6-411e72a38c92.png)

When I press the Ok-button, the dialog disappears nothing else happens.

This is what Control Panel tells me about Divvun installer
![divvun installer control panel](https://user-images.githubusercontent.com/75695/91845774-0c8cfe80-ec5a-11ea-84dc-e5e189e1a9bc.png)

and the lule sami speller
![lule sami speller](https://user-images.githubusercontent.com/75695/91845822-22022880-ec5a-11ea-8744-ed3aa8fadb72.png)

OS: Windows 10 Enterprise
Version: 10.0.18363 Build 18363

**Comment by bbqsrc** [comment]
> The installation of those stopped with an error (did not take a screenshot of that error message).

I suspect this error was important. 😛  The screenshot you present now indicates that the Pahkat Service probably isn't running, which may be related to you running nightly versions which were not stable (truly, two of them broke things badly, hence nightly hehe).

So let's cleanup first to a clean state and try again. From the Windows add/remove programs, uninstall the following things (in the order specified):

- North Sami Speller (if found)
- Lule Sami speller
- WinDivvun
- Divvun Installer
- Pahkat Service (if it still exists)

Then reboot, install Divvun Installer 2.0 again.

From that point, do as you did before: install North Sami and Lule Sami at the same time. Take screenshots of ANY errors you find along the way.

**Comment by albbas** [comment]
Did the changes, reinstalled and started Divvun installer.
Had to chose All repositories to see any packages.
Installed lule and north sami speller and north sami keyboard. Everything went smooth, no error messages.

**Comment by bbqsrc** [comment]
The webview was blank on first run? Good to know the caching bug is still being a pain.

**Comment by albbas** [comment]
> The webview was blank on first run? Good to know the caching bug is still being a pain.
Yep. And even if I change back from All repos to Divvun Languages, the screen is still blank.

**Comment by bbqsrc** [comment]
See #15 and we can work on that there. 😄
