### ISSUE TITLE
Divvun installer pref view is almost empty of content

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-installer-windows#5]
<img width="597" alt="Skjermbilde 2020-05-23 kl  12 02 16" src="https://user-images.githubusercontent.com/1255285/82726526-70b03600-9ced-11ea-8702-164d13e9c928.png">

Locale: nynorsk.

**Comment by snomos** [comment]
This is only in dark mode. In light/bright mode, the pref view looks like this:

<img width="598" alt="Skjermbilde 2020-05-23 kl  12 33 13" src="https://user-images.githubusercontent.com/1255285/82727204-c1299280-9cf1-11ea-829a-371750bed089.png">

which seems to be correct.

**Comment by bbqsrc** [comment]
👌

**Comment by bbqsrc** [comment]
fixed in https://github.com/divvun/divvun-installer-windows/commit/6e8a5ebfd239f591a9bf8d7d21420426f0ffd31e
