### ISSUE TITLE
Divvun installer all repo view hard to read in dark mode

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-installer-windows#6]
<img width="1354" alt="Skjermbilde 2020-05-23 kl  12 13 01" src="https://user-images.githubusercontent.com/1255285/82727001-57f54f80-9cf0-11ea-8c96-ea19c82f8bfd.png">

**Comment by bbqsrc** [comment]
fixed in https://github.com/divvun/divvun-installer-windows/commit/6e8a5ebfd239f591a9bf8d7d21420426f0ffd31e
